/// Flutter icons Details
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Details
///      fonts:
///       - asset: fonts/Details.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Details {
  Details._();

  static const _kFontFam = 'Details';

  static const IconData comment = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData price = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData female = const IconData(0xf182, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xf183, fontFamily: _kFontFam);
}
