/// Flutter icons MoreIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MoreIcons
///      fonts:
///       - asset: fonts/MoreIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MoreIcons {
  MoreIcons._();

  static const _kFontFam = 'MoreIcons';

  static const IconData tshirt = IconData(0xe801, fontFamily: _kFontFam, );
  static const IconData drawer = IconData(0xe802, fontFamily: _kFontFam, );
}
