/// Flutter icons NavBarIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NavBarIcon
///      fonts:
///       - asset: fonts/NavBarIcon.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class NavBarIcon {
  NavBarIcon._();

  static const _kFontFam = 'NavBarIcon';

  static const IconData order = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData qrcode = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData domore = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData map = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData shoppingcart = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData female = const IconData(0xf182, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xf183, fontFamily: _kFontFam);
}
