/// Flutter icons Profile
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Profile
///      fonts:
///       - asset: fonts/Profile.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Profile {
  Profile._();

  static const _kFontFam = 'Profile';

  static const IconData vouchers = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData wallet = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData cash = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData loyallevel = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData notification = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData offers = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData pointsconvert = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData female = const IconData(0xf182, fontFamily: _kFontFam);
  static const IconData male = const IconData(0xf183, fontFamily: _kFontFam);
}
