/// Flutter icons Setting
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Setting
///      fonts:
///       - asset: fonts/Setting.ttf
///
/// 
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Setting {
  Setting._();

  static const _kFontFam = 'Setting';

  static const IconData logout = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData rateus = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData socialize = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData licence = const IconData(0xe809, fontFamily: _kFontFam);
}
